linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - typecheck
    - misspell
    - gocritic
    - revive
    - unused

linters-settings:
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
    check-blank: false
  gocritic:
    disabled-checks:
      - ifElseChain
      - assignOp
      - dupBranchBody
      - unlambda
      - dupArg
  revive:
    rules:
      - name: increment-decrement
        disabled: true
      - name: redefines-builtin-id
        disabled: true

issues:
  exclude-dirs:
    - benchmarks/generated
    - benchmarks/curated
    - benchmarks/mass_generated
    - examples/generated
    - output
    - vendor

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic

    - path: cmd/
      linters:
        - errcheck
        - gocritic


  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
