package regengo

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCompile(t *testing.T) {
	tests := []struct {
		name    string
		pattern string
		wantErr bool
	}{
		{
			name:    "simple pattern",
			pattern: "test",
			wantErr: false,
		},
		{
			name:    "email pattern",
			pattern: `[\w\.+-]+@[\w\.-]+\.[\w\.-]+`,
			wantErr: false,
		},
		{
			name:    "digit pattern",
			pattern: `\d+`,
			wantErr: false,
		},
		{
			name:    "invalid pattern",
			pattern: "[invalid",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			outputFile := filepath.Join(tmpDir, "test.go")

			opts := Options{
				Pattern:    tt.pattern,
				Name:       "Test",
				OutputFile: outputFile,
				Package:    "test",
			}

			err := Compile(opts)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Errorf("unexpected error: %v", err)
				return
			}

			// Verify output file exists
			if _, err := os.Stat(outputFile); os.IsNotExist(err) {
				t.Error("output file was not created")
			}

			// Verify output file contains expected functions
			content, err := os.ReadFile(outputFile)
			if err != nil {
				t.Errorf("failed to read output file: %v", err)
				return
			}

			contentStr := string(content)
			if !strings.Contains(contentStr, "func (Test) MatchString") {
				t.Error("output file does not contain MatchString method")
			}
			if !strings.Contains(contentStr, "func (Test) MatchBytes") {
				t.Error("output file does not contain MatchBytes method")
			}
		})
	}
}

func TestOptionsValidation(t *testing.T) {
	tests := []struct {
		name    string
		opts    Options
		wantErr bool
	}{
		{
			name: "valid options",
			opts: Options{
				Pattern:    "test",
				Name:       "Test",
				OutputFile: "test.go",
				Package:    "test",
			},
			wantErr: false,
		},
		{
			name: "empty pattern",
			opts: Options{
				Name:       "Test",
				OutputFile: "test.go",
				Package:    "test",
			},
			wantErr: true,
		},
		{
			name: "empty name",
			opts: Options{
				Pattern:    "test",
				OutputFile: "test.go",
				Package:    "test",
			},
			wantErr: true,
		},
		{
			name: "empty output file",
			opts: Options{
				Pattern: "test",
				Name:    "Test",
				Package: "test",
			},
			wantErr: true,
		},
		{
			name: "empty package",
			opts: Options{
				Pattern:    "test",
				Name:       "Test",
				OutputFile: "test.go",
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.opts.Validate()
			if tt.wantErr && err == nil {
				t.Error("expected validation error but got none")
			}
			if !tt.wantErr && err != nil {
				t.Errorf("unexpected validation error: %v", err)
			}
		})
	}
}

func TestCompileIntegration(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}

	tmpDir := t.TempDir()
	outputFile := filepath.Join(tmpDir, "email.go")

	opts := Options{
		Pattern:    `[\w\.+-]+@[\w\.-]+\.[\w\.-]+`,
		Name:       "Email",
		OutputFile: outputFile,
		Package:    "emailtest",
	}

	if err := Compile(opts); err != nil {
		t.Fatalf("compilation failed: %v", err)
	}

	// Read and verify the generated code
	content, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	contentStr := string(content)

	// Check for expected elements
	expectedElements := []string{
		"package emailtest",
		"func (Email) MatchString(input string) bool",
		"func (Email) MatchBytes(input []byte) bool",
		"// Code generated by regengo",
		"DO NOT EDIT",
	}

	for _, elem := range expectedElements {
		if !strings.Contains(contentStr, elem) {
			t.Errorf("generated code missing expected element: %q", elem)
		}
	}
}

func TestCompileWithReplacers(t *testing.T) {
	tests := []struct {
		name        string
		pattern     string
		replacers   []string
		wantErr     bool
		errContains string
	}{
		// Valid cases
		{
			name:      "simple replacer with named capture",
			pattern:   `(?P<x>\w+)`,
			replacers: []string{"[$x]"},
			wantErr:   false,
		},
		{
			name:      "multiple replacers",
			pattern:   `(?P<x>\w+)`,
			replacers: []string{"$x", "[$0]", "REDACTED"},
			wantErr:   false,
		},
		{
			name:      "full match only - no captures",
			pattern:   `\d+`,
			replacers: []string{"[NUMBER]"},
			wantErr:   false,
		},
		{
			name:      "full match $0 - no captures",
			pattern:   `\d+`,
			replacers: []string{"[$0]"},
			wantErr:   false,
		},
		{
			name:      "no replacers - nil",
			pattern:   `(?P<x>\w+)`,
			replacers: nil,
			wantErr:   false,
		},
		{
			name:      "no replacers - empty slice",
			pattern:   `(?P<x>\w+)`,
			replacers: []string{},
			wantErr:   false,
		},
		{
			name:      "indexed capture",
			pattern:   `(\w+)@(\w+)`,
			replacers: []string{"$1 at $2"},
			wantErr:   false,
		},
		{
			name:      "escaped dollar",
			pattern:   `\d+`,
			replacers: []string{"$$100"},
			wantErr:   false,
		},

		// Invalid cases
		{
			name:        "invalid named ref",
			pattern:     `(?P<x>\w+)`,
			replacers:   []string{"$y"},
			wantErr:     true,
			errContains: `"y"`,
		},
		{
			name:        "invalid index - too high",
			pattern:     `(?P<x>\w+)`,
			replacers:   []string{"$2"},
			wantErr:     true,
			errContains: "capture group 2",
		},
		{
			name:        "malformed template - unclosed brace",
			pattern:     `(?P<x>\w+)`,
			replacers:   []string{"${unclosed"},
			wantErr:     true,
			errContains: "unclosed",
		},
		{
			name:        "malformed template - empty braces",
			pattern:     `(?P<x>\w+)`,
			replacers:   []string{"${}"},
			wantErr:     true,
			errContains: "empty",
		},
		{
			name:        "second replacer invalid",
			pattern:     `(?P<x>\w+)`,
			replacers:   []string{"$x", "$invalid"},
			wantErr:     true,
			errContains: "replacer[1]",
		},
		{
			name:        "index on pattern without captures",
			pattern:     `\d+`,
			replacers:   []string{"$1"},
			wantErr:     true,
			errContains: "capture group 1",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			outputFile := filepath.Join(tmpDir, "test.go")

			opts := Options{
				Pattern:    tt.pattern,
				Name:       "Test",
				OutputFile: outputFile,
				Package:    "test",
				Replacers:  tt.replacers,
			}

			err := Compile(opts)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
					return
				}
				if tt.errContains != "" && !strings.Contains(err.Error(), tt.errContains) {
					t.Errorf("error %q should contain %q", err.Error(), tt.errContains)
				}
				return
			}

			if err != nil {
				t.Errorf("unexpected error: %v", err)
				return
			}

			// Verify output file exists for successful compilations
			if _, err := os.Stat(outputFile); os.IsNotExist(err) {
				t.Error("output file was not created")
			}
		})
	}
}
