package testdata

import (
	"bytes"
	"fmt"
	replace "github.com/KromDaniel/regengo/replace"
	stream "github.com/KromDaniel/regengo/stream"
	"io"
	"strings"
)

// Code generated by regengo for pattern: (\d{4}-\d{2}-\d{2})
// DO NOT EDIT.

type DatePattern struct{}

var CompiledDatePattern = DatePattern{}

// MinMatchLen is the minimum number of bytes any match can have.
const DatePatternMinMatchLen = 10

// MaxMatchLen is the maximum number of bytes any match can have.
// -1 means unbounded (pattern contains * or + quantifiers).
const DatePatternMaxMatchLen = 10

func (DatePattern) MatchLengthInfo() (minLen, maxLen int) {
	return DatePatternMinMatchLen, DatePatternMaxMatchLen
}

func (DatePattern) MatchString(input string) bool {
	l := len(input)
	offset := 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if l > offset {
		nextInstruction = 1
		offset++
		goto StepSelect
	}
	return false
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		goto Ins2
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins4
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins5
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		goto Ins13
	}
Ins13:
	{
		return true
	}
}
func (DatePattern) MatchBytes(input []byte) bool {
	l := len(input)
	offset := 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if l > offset {
		nextInstruction = 1
		offset++
		goto StepSelect
	}
	return false
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		goto Ins2
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins4
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins5
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		goto Ins13
	}
Ins13:
	{
		return true
	}
}

type DatePatternResult struct {
	Match  string // Full match
	Group1 string
}

type DatePatternBytesResult struct {
	Match  []byte // Full match
	Group1 []byte
}

func (DatePattern) FindStringReuse(input string, r *DatePatternResult) (*DatePatternResult, bool) {
	l := len(input)
	offset := 0
	var captures [4]int
	captures[0] = 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if l > offset {
		offset++
		for i := range captures {
			captures[i] = 0
		}
		captures[0] = offset
		nextInstruction = 1
		goto StepSelect
	}
	return nil, false
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return nil, false
	}
Ins1:
	{
		captures[2] = offset
		nextInstruction = 2
		goto StepSelect
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins4
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins5
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		captures[3] = offset
		nextInstruction = 13
		goto StepSelect
	}
Ins13:
	{
		captures[1] = offset
		if r == nil {
			r = &DatePatternResult{}
		}
		r.Match = string(input[captures[0]:captures[1]])
		if captures[2] <= captures[3] && captures[3] <= len(input) {
			r.Group1 = string(input[captures[2]:captures[3]])
		} else {
			r.Group1 = ""
		}
		return r, true
	}
}
func (recv DatePattern) FindString(input string) (*DatePatternResult, bool) {
	return recv.FindStringReuse(input, nil)
}
func (DatePattern) FindAllStringAppend(input string, n int, s []*DatePatternResult) []*DatePatternResult {
	if n == 0 {
		return s
	}
	result := s
	l := len(input)
	searchStart := 0
	for true {
		if n > 0 && len(result) >= n {
			break
		}
		if searchStart >= l {
			break
		}
		offset := searchStart
		var captures [4]int
		captures[0] = searchStart
		nextInstruction := 1
		goto StepSelect
	TryFallback:
		searchStart++
		continue
	StepSelect:
		switch nextInstruction {
		case 0:
			goto Ins0
		case 1:
			goto Ins1
		case 2:
			goto Ins2
		case 3:
			goto Ins3
		case 4:
			goto Ins4
		case 5:
			goto Ins5
		case 6:
			goto Ins6
		case 7:
			goto Ins7
		case 8:
			goto Ins8
		case 9:
			goto Ins9
		case 10:
			goto Ins10
		case 11:
			goto Ins11
		case 12:
			goto Ins12
		case 13:
			goto Ins13
		}
	Ins0:
		{
			goto TryFallback
		}
	Ins1:
		{
			captures[2] = offset
			nextInstruction = 2
			goto StepSelect
		}
	Ins2:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins3
		}
	Ins3:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins4
		}
	Ins4:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins5
		}
	Ins5:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins6
		}
	Ins6:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x2d) {
				goto TryFallback
			}
			offset++
			goto Ins7
		}
	Ins7:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins8
		}
	Ins8:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins9
		}
	Ins9:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x2d) {
				goto TryFallback
			}
			offset++
			goto Ins10
		}
	Ins10:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins11
		}
	Ins11:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins12
		}
	Ins12:
		{
			captures[3] = offset
			nextInstruction = 13
			goto StepSelect
		}
	Ins13:
		{
			captures[1] = offset
			var item *DatePatternResult
			if len(result) < cap(result) {
				result = result[:len(result)+1]
				item = result[len(result)-1]
				if item == nil {
					item = &DatePatternResult{}
					result[len(result)-1] = item
				}
			} else {
				item = &DatePatternResult{}
				result = append(result, item)
			}
			item.Match = string(input[captures[0]:captures[1]])
			if captures[2] <= captures[3] && captures[3] <= len(input) {
				item.Group1 = string(input[captures[2]:captures[3]])
			} else {
				item.Group1 = ""
			}
			if captures[1] > searchStart {
				searchStart = captures[1]
			} else {
				searchStart++
			}
			continue
		}
	}
	return result
}
func (r DatePattern) FindAllString(input string, n int) []*DatePatternResult {
	return r.FindAllStringAppend(input, n, nil)
}
func (DatePattern) FindBytesReuse(input []byte, r *DatePatternBytesResult) (*DatePatternBytesResult, bool) {
	l := len(input)
	offset := 0
	var captures [4]int
	captures[0] = 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if l > offset {
		offset++
		for i := range captures {
			captures[i] = 0
		}
		captures[0] = offset
		nextInstruction = 1
		goto StepSelect
	}
	return nil, false
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return nil, false
	}
Ins1:
	{
		captures[2] = offset
		nextInstruction = 2
		goto StepSelect
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins4
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins5
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2d) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		captures[3] = offset
		nextInstruction = 13
		goto StepSelect
	}
Ins13:
	{
		captures[1] = offset
		if r == nil {
			r = &DatePatternBytesResult{}
		}
		r.Match = input[captures[0]:captures[1]]
		if captures[2] <= captures[3] && captures[3] <= len(input) {
			r.Group1 = input[captures[2]:captures[3]]
		} else {
			r.Group1 = nil
		}
		return r, true
	}
}
func (recv DatePattern) FindBytes(input []byte) (*DatePatternBytesResult, bool) {
	return recv.FindBytesReuse(input, nil)
}
func (DatePattern) FindAllBytesAppend(input []byte, n int, s []*DatePatternBytesResult) []*DatePatternBytesResult {
	if n == 0 {
		return s
	}
	result := s
	l := len(input)
	searchStart := 0
	for true {
		if n > 0 && len(result) >= n {
			break
		}
		if searchStart >= l {
			break
		}
		offset := searchStart
		var captures [4]int
		captures[0] = searchStart
		nextInstruction := 1
		goto StepSelect
	TryFallback:
		searchStart++
		continue
	StepSelect:
		switch nextInstruction {
		case 0:
			goto Ins0
		case 1:
			goto Ins1
		case 2:
			goto Ins2
		case 3:
			goto Ins3
		case 4:
			goto Ins4
		case 5:
			goto Ins5
		case 6:
			goto Ins6
		case 7:
			goto Ins7
		case 8:
			goto Ins8
		case 9:
			goto Ins9
		case 10:
			goto Ins10
		case 11:
			goto Ins11
		case 12:
			goto Ins12
		case 13:
			goto Ins13
		}
	Ins0:
		{
			goto TryFallback
		}
	Ins1:
		{
			captures[2] = offset
			nextInstruction = 2
			goto StepSelect
		}
	Ins2:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins3
		}
	Ins3:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins4
		}
	Ins4:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins5
		}
	Ins5:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins6
		}
	Ins6:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x2d) {
				goto TryFallback
			}
			offset++
			goto Ins7
		}
	Ins7:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins8
		}
	Ins8:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins9
		}
	Ins9:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x2d) {
				goto TryFallback
			}
			offset++
			goto Ins10
		}
	Ins10:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins11
		}
	Ins11:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
				goto TryFallback
			}
			offset++
			goto Ins12
		}
	Ins12:
		{
			captures[3] = offset
			nextInstruction = 13
			goto StepSelect
		}
	Ins13:
		{
			captures[1] = offset
			var item *DatePatternBytesResult
			if len(result) < cap(result) {
				result = result[:len(result)+1]
				item = result[len(result)-1]
				if item == nil {
					item = &DatePatternBytesResult{}
					result[len(result)-1] = item
				}
			} else {
				item = &DatePatternBytesResult{}
				result = append(result, item)
			}
			item.Match = input[captures[0]:captures[1]]
			if captures[2] <= captures[3] && captures[3] <= len(input) {
				item.Group1 = input[captures[2]:captures[3]]
			} else {
				item.Group1 = nil
			}
			if captures[1] > searchStart {
				searchStart = captures[1]
			} else {
				searchStart++
			}
			continue
		}
	}
	return result
}
func (r DatePattern) FindAllBytes(input []byte, n int) []*DatePatternBytesResult {
	return r.FindAllBytesAppend(input, n, nil)
}

// DefaultMaxLeftover returns the recommended MaxLeftover value for streaming.
// For bounded patterns, this is 10 * MaxMatchLen.
// For unbounded patterns, this returns 1MB as a safety limit.
func (DatePattern) DefaultMaxLeftover() int {
	return 1024
}

// FindReader streams matches from an io.Reader.
//
// The onMatch callback is called for each match found. Return false to stop
// processing early. The StreamMatch.Result points into an internal buffer
// and is only valid during the callback - copy if needed.
//
// Returns nil on success (including early termination via callback).
// Returns error on read failure.
func (DatePattern) FindReader(r io.Reader, cfg stream.Config, onMatch func(stream.Match[*DatePatternBytesResult]) bool) error {
	if err := cfg.Validate(65536); err != nil {
		return err
	}
	cfg = cfg.ApplyDefaults(65536, 1024)

	buf := make([]byte, cfg.BufferSize)
	leftover := 0
	streamOffset := int64(0)
	chunkIndex := 0

	reuseResult := &DatePatternBytesResult{}

	for {
		n, err := r.Read(buf[leftover:])
		if n == 0 && err != nil {
			if err == io.EOF {
				// Process any remaining data in leftover
				if leftover > 0 {
					chunk := buf[:leftover]
					searchPos := 0
					for searchPos < len(chunk) {
						result, ok := DatePattern{}.FindBytesReuse(chunk[searchPos:], reuseResult)
						if !ok {
							break
						}
						matchIdx := bytes.Index(chunk[searchPos:], result.Match)
						if matchIdx < 0 {
							break
						}
						matchStart := searchPos + matchIdx

						m := stream.Match[*DatePatternBytesResult]{
							ChunkIndex:   chunkIndex,
							Result:       result,
							StreamOffset: streamOffset + int64(matchStart),
						}
						if !onMatch(m) {
							return nil
						}
						if len(result.Match) > 0 {
							searchPos = matchStart + len(result.Match)
						} else {
							searchPos++
						}
					}
				}
				return nil
			}
			return err
		}

		dataLen := leftover + n
		chunk := buf[:dataLen]
		isFull := n == cfg.BufferSize-leftover

		searchPos := 0
		committed := 0
		for searchPos < len(chunk) {
			result, ok := DatePattern{}.FindBytesReuse(chunk[searchPos:], reuseResult)
			if !ok {
				break
			}
			matchIdx := bytes.Index(chunk[searchPos:], result.Match)
			if matchIdx < 0 {
				break
			}
			matchStart := searchPos + matchIdx
			matchEnd := matchStart + len(result.Match)

			if isFull && matchEnd > dataLen-cfg.MaxLeftover {
				// Match too close to boundary, defer to next chunk
				break
			}

			m := stream.Match[*DatePatternBytesResult]{
				ChunkIndex:   chunkIndex,
				Result:       result,
				StreamOffset: streamOffset + int64(matchStart),
			}
			if !onMatch(m) {
				return nil
			}
			committed = matchEnd
			if len(result.Match) > 0 {
				searchPos = matchEnd
			} else {
				searchPos++
			}
		}

		// Prepare leftover for next iteration
		if isFull {
			// Buffer was full, need to keep leftover
			keepFrom := dataLen - cfg.MaxLeftover
			if keepFrom < committed {
				keepFrom = committed
			}
			leftover = dataLen - keepFrom
			streamOffset += int64(keepFrom)
			copy(buf[:leftover], buf[keepFrom:dataLen])
		} else {
			// Reached EOF or short read, no more data
			leftover = 0
		}
		chunkIndex++
		if err == io.EOF {
			return nil
		}
	}
}

// FindReaderCount counts matches without allocating result structs.
// More efficient when you only need the count.
func (DatePattern) FindReaderCount(r io.Reader, cfg stream.Config) (int64, error) {
	var count int64
	err := DatePattern{}.FindReader(r, cfg, func(_ stream.Match[*DatePatternBytesResult]) bool {
		count++
		return true
	})
	return count, err
}

// FindReaderFirst returns the first match, or nil if none found.
// The returned result is a copy (safe to use after call returns).
func (DatePattern) FindReaderFirst(r io.Reader, cfg stream.Config) (*DatePatternBytesResult, int64, error) {
	var result *DatePatternBytesResult
	var offset int64
	err := DatePattern{}.FindReader(r, cfg, func(m stream.Match[*DatePatternBytesResult]) bool {
		// Copy the result since buffer will be reused
		result = DatePattern{}.copyBytesResult(m.Result)
		offset = m.StreamOffset
		return false
	})
	return result, offset, err
}

// copyBytesResult creates a deep copy of a BytesResult.
// This is needed because the original slices point into the stream buffer.
func (DatePattern) copyBytesResult(src *DatePatternBytesResult) *DatePatternBytesResult {
	if src == nil {
		return nil
	}
	dst := &DatePatternBytesResult{}
	// Copy Match slice
	dst.Match = append([]byte{}, src.Match...)
	return dst
}

// NewTransformReader returns an io.Reader that transforms matches in the input stream.
//
// The onMatch callback is called for each match. Use emit to output replacement bytes.
// If emit is not called, the match is dropped (filter behavior).
// Non-matching segments are automatically passed through to output.
//
// Example usage:
//
//	r := pattern.NewTransformReader(input, stream.DefaultTransformConfig(),
//	    func(m *PatternBytesResult, emit func([]byte)) {
//	        emit([]byte("REDACTED"))
//	    })
//	io.Copy(os.Stdout, r)
func (DatePattern) NewTransformReader(r io.Reader, cfg stream.TransformConfig, onMatch func(match *DatePatternBytesResult, emit func([]byte))) io.Reader {
	if cfg.BufferSize == 0 {
		cfg.BufferSize = 65536
	}
	if cfg.MaxLeftover == 0 {
		cfg.MaxLeftover = 1024
	}

	processor := func(data []byte, isEOF bool, _ stream.TransformFunc, emitOut func([]byte)) int {
		return DatePattern{}.processTransform(data, isEOF, onMatch, emitOut)
	}

	return stream.NewTransformer(r, cfg, processor, func(_ []byte, emit func([]byte)) {})
}

// processTransform processes data for transformation.
func (DatePattern) processTransform(data []byte, isEOF bool, onMatch func(match *DatePatternBytesResult, emit func([]byte)), emitOut func([]byte)) int {
	processed := 0
	reuseResult := &DatePatternBytesResult{}

	for {
		result, ok := DatePattern{}.FindBytesReuse(data[processed:], reuseResult)
		if !ok {
			// No more matches
			if isEOF {
				if processed < len(data) {
					emitOut(data[processed:])
				}
				return len(data)
			}
			// Keep potential partial match data
			safePoint := len(data) - 102
			if safePoint < processed {
				safePoint = processed
			}
			if safePoint > processed {
				emitOut(data[processed:safePoint])
			}
			return safePoint
		}

		matchIdx := bytes.Index(data[processed:], result.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := processed + matchIdx
		matchEnd := matchStart + len(result.Match)

		if matchStart > processed {
			emitOut(data[processed:matchStart])
		}

		onMatch(result, emitOut)

		if len(result.Match) > 0 {
			processed = matchEnd
		} else {
			processed++
		}
	}
	return processed
}

// ReplaceReader returns an io.Reader that replaces all matches with the template.
//
// Template syntax:
//
//	$0 or ${0}: full match
//	$1, $2, ...: capture group by index
//	$name or ${name}: capture group by name
//	$$: literal dollar sign
//
// Example:
//
//	r := pattern.ReplaceReader(input, "[$1]")
//	io.Copy(os.Stdout, r)
func (DatePattern) ReplaceReader(r io.Reader, template string) io.Reader {
	parsed, err := replace.Parse(template)
	if err != nil {
		return &datePatternTransformErrReader{err: err}
	}

	captureNames := map[string]int{}
	resolved, err := parsed.ValidateAndResolve(captureNames, 1)
	if err != nil {
		return &datePatternTransformErrReader{err: err}
	}

	return DatePattern{}.NewTransformReader(r, stream.DefaultTransformConfig(), func(m *DatePatternBytesResult, emit func([]byte)) {
		result := make([]byte, 0, len(template)+64)
		for _, seg := range resolved {
			switch seg.Type {
			case replace.SegmentLiteral:
				result = append(result, seg.Literal...)
			case replace.SegmentFullMatch:
				result = append(result, m.Match...)
			case replace.SegmentCaptureIndex:
				capture := (DatePattern{}).getCaptureByIndex(m, seg.CaptureIndex)
				if capture != nil {
					result = append(result, capture...)
				}
			}
		}
		emit(result)
	})
}

// datePatternTransformErrReader is a reader that always returns an error.
type datePatternTransformErrReader struct {
	err error
}

func (r *datePatternTransformErrReader) Read(p []byte) (int, error) {
	return 0, r.err
}

// getCaptureByIndex returns the capture group value by its index.
func (DatePattern) getCaptureByIndex(m *DatePatternBytesResult, index int) []byte {
	switch index {
	case 0:
		return m.Match
	default:
		return nil
	}
}

// SelectReader returns an io.Reader that outputs only matches satisfying the predicate.
// Non-matching segments are dropped. Only matches where pred returns true are output.
//
// Example - extract all email addresses:
//
//	r := emailPattern.SelectReader(input, func(m *EmailBytesResult) bool {
//	    return true // Keep all matches
//	})
func (DatePattern) SelectReader(r io.Reader, pred func(*DatePatternBytesResult) bool) io.Reader {
	cfg := stream.DefaultTransformConfig()
	cfg.MaxLeftover = 1024

	processor := func(data []byte, isEOF bool, _ stream.TransformFunc, emitOut func([]byte)) int {
		return DatePattern{}.processSelect(data, isEOF, pred, emitOut)
	}

	return stream.NewTransformer(r, cfg, processor, func(_ []byte, emit func([]byte)) {})
}

// processSelect processes data for select filtering.
func (DatePattern) processSelect(data []byte, isEOF bool, pred func(*DatePatternBytesResult) bool, emitOut func([]byte)) int {
	processed := 0
	reuseResult := &DatePatternBytesResult{}

	for {
		result, ok := DatePattern{}.FindBytesReuse(data[processed:], reuseResult)
		if !ok {
			if isEOF {
				return len(data)
			}
			return processed
		}

		matchIdx := bytes.Index(data[processed:], result.Match)
		if matchIdx < 0 {
			break
		}

		matchEnd := processed + matchIdx + len(result.Match)

		if pred(result) {
			emitOut(result.Match)
		}

		if len(result.Match) > 0 {
			processed = matchEnd
		} else {
			processed++
		}
	}
	return processed
}

// RejectReader returns an io.Reader that removes matches satisfying the predicate.
// Non-matching segments pass through. Matches where pred returns true are dropped.
//
// Example - remove all sensitive data:
//
//	r := sensitivePattern.RejectReader(input, func(m *SensitiveBytesResult) bool {
//	    return true // Remove all matches
//	})
func (DatePattern) RejectReader(r io.Reader, pred func(*DatePatternBytesResult) bool) io.Reader {
	cfg := stream.DefaultTransformConfig()
	cfg.MaxLeftover = 1024

	processor := func(data []byte, isEOF bool, _ stream.TransformFunc, emitOut func([]byte)) int {
		return DatePattern{}.processReject(data, isEOF, pred, emitOut)
	}

	return stream.NewTransformer(r, cfg, processor, func(_ []byte, emit func([]byte)) {})
}

// processReject processes data for reject filtering.
func (DatePattern) processReject(data []byte, isEOF bool, pred func(*DatePatternBytesResult) bool, emitOut func([]byte)) int {
	processed := 0
	reuseResult := &DatePatternBytesResult{}

	for {
		result, ok := DatePattern{}.FindBytesReuse(data[processed:], reuseResult)
		if !ok {
			if isEOF {
				if processed < len(data) {
					emitOut(data[processed:])
				}
				return len(data)
			}
			safePoint := len(data) - 102
			if safePoint < processed {
				safePoint = processed
			}
			if safePoint > processed {
				emitOut(data[processed:safePoint])
			}
			return safePoint
		}

		matchIdx := bytes.Index(data[processed:], result.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := processed + matchIdx
		matchEnd := matchStart + len(result.Match)

		if matchStart > processed {
			emitOut(data[processed:matchStart])
		}

		if !pred(result) {
			emitOut(result.Match)
		}

		if len(result.Match) > 0 {
			processed = matchEnd
		} else {
			processed++
		}
	}
	return processed
}

// CaptureByIndex returns the capture group value by its 0-based index.
// Index 0 returns the full match, 1+ returns capture groups.
func (r *DatePatternResult) CaptureByIndex(idx int) string {
	switch idx {
	case 0:
		return r.Match
	case 1:
		return r.Group1
	default:
		return ""
	}
}

// CaptureByIndex returns the capture group value by its 0-based index.
// Index 0 returns the full match, 1+ returns capture groups.
func (r *DatePatternBytesResult) CaptureByIndex(idx int) []byte {
	switch idx {
	case 0:
		return r.Match
	case 1:
		return r.Group1
	default:
		return nil
	}
}

// ReplaceAllString replaces all matches in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (DatePattern) ReplaceAllString(input string, template string) string {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	var result strings.Builder
	lastEnd := 0
	var r DatePatternResult

	remaining := input
	offset := 0

	for {
		match, ok := DatePattern{}.FindStringReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := strings.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := offset + matchIdx
		matchEnd := matchStart + len(match.Match)

		result.WriteString(input[lastEnd:matchStart])

		for _, seg := range tmpl.Segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result.WriteString(seg.Literal)
			case replace.SegmentFullMatch:
				result.WriteString(match.Match)
			case replace.SegmentCaptureIndex:
				result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
			case replace.SegmentCaptureName:
				// No named captures in pattern
			}
		}

		lastEnd = matchEnd
		if len(match.Match) > 0 {
			remaining = input[matchEnd:]
			offset = matchEnd
		} else {
			if matchEnd < len(input) {
				remaining = input[matchEnd+1:]
				offset = matchEnd + 1
			} else {
				break
			}
		}
	}

	result.WriteString(input[lastEnd:])
	return result.String()
}

// ReplaceAllBytes replaces all matches in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (DatePattern) ReplaceAllBytes(input []byte, template string) []byte {
	return DatePattern{}.ReplaceAllBytesAppend(input, template, nil)
}

// ReplaceAllBytesAppend replaces all matches and appends to buf.
// If buf has sufficient capacity, no allocation occurs.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (DatePattern) ReplaceAllBytesAppend(input []byte, template string, buf []byte) []byte {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	result := buf[:0]
	lastEnd := 0
	var r DatePatternBytesResult

	remaining := input
	offset := 0

	for {
		match, ok := DatePattern{}.FindBytesReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := bytes.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := offset + matchIdx
		matchEnd := matchStart + len(match.Match)

		result = append(result, input[lastEnd:matchStart]...)

		for _, seg := range tmpl.Segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result = append(result, seg.Literal...)
			case replace.SegmentFullMatch:
				result = append(result, match.Match...)
			case replace.SegmentCaptureIndex:
				result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
			case replace.SegmentCaptureName:
				// No named captures in pattern
			}
		}

		lastEnd = matchEnd
		if len(match.Match) > 0 {
			remaining = input[matchEnd:]
			offset = matchEnd
		} else {
			if matchEnd < len(input) {
				remaining = input[matchEnd+1:]
				offset = matchEnd + 1
			} else {
				break
			}
		}
	}

	result = append(result, input[lastEnd:]...)
	return result
}

// ReplaceFirstString replaces only the first match in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (DatePattern) ReplaceFirstString(input string, template string) string {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	var r DatePatternResult
	match, ok := DatePattern{}.FindStringReuse(input, &r)
	if !ok {
		return input
	}

	matchIdx := strings.Index(input, match.Match)
	if matchIdx < 0 {
		return input
	}

	var result strings.Builder
	result.WriteString(input[:matchIdx])

	for _, seg := range tmpl.Segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result.WriteString(seg.Literal)
		case replace.SegmentFullMatch:
			result.WriteString(match.Match)
		case replace.SegmentCaptureIndex:
			result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
		case replace.SegmentCaptureName:
			// No named captures in pattern
		}
	}

	result.WriteString(input[matchIdx+len(match.Match):])
	return result.String()
}

// ReplaceFirstBytes replaces only the first match in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (DatePattern) ReplaceFirstBytes(input []byte, template string) []byte {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	var r DatePatternBytesResult
	match, ok := DatePattern{}.FindBytesReuse(input, &r)
	if !ok {
		return append([]byte{}, input...)
	}

	matchIdx := bytes.Index(input, match.Match)
	if matchIdx < 0 {
		return append([]byte{}, input...)
	}

	var result []byte
	result = append(result, input[:matchIdx]...)

	for _, seg := range tmpl.Segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result = append(result, seg.Literal...)
		case replace.SegmentFullMatch:
			result = append(result, match.Match...)
		case replace.SegmentCaptureIndex:
			result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
		case replace.SegmentCaptureName:
			// No named captures in pattern
		}
	}

	result = append(result, input[matchIdx+len(match.Match):]...)
	return result
}

// DatePatternReplaceTemplate holds a pre-compiled replace template for the DatePattern pattern.
// Use CompileReplaceTemplate to create one, then call its Replace methods.
type DatePatternReplaceTemplate struct {
	original string
	segments []replace.Segment
}

// CompileReplaceTemplate parses and validates a replace template.
// Returns an error if the template syntax is invalid or references non-existent captures.
// The compiled template can be reused for multiple replacements without re-parsing.
//
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (DatePattern) CompileReplaceTemplate(template string) (*DatePatternReplaceTemplate, error) {
	tmpl, err := replace.Parse(template)
	if err != nil {
		return nil, err
	}

	captureNames := map[string]int{}

	resolved, err := tmpl.ValidateAndResolve(captureNames, 1)
	if err != nil {
		return nil, err
	}

	return &DatePatternReplaceTemplate{
		original: template,
		segments: resolved,
	}, nil
}

// String returns the original template string.
func (t *DatePatternReplaceTemplate) String() string {
	return t.original
}

// ReplaceAllString replaces all matches in input using this compiled template.
func (t *DatePatternReplaceTemplate) ReplaceAllString(input string) string {
	var result strings.Builder
	lastEnd := 0
	var r DatePatternResult

	remaining := input
	offset := 0

	for {
		match, ok := DatePattern{}.FindStringReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := strings.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		absMatchStart := offset + matchIdx
		absMatchEnd := absMatchStart + len(match.Match)

		result.WriteString(input[lastEnd:absMatchStart])

		for _, seg := range t.segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result.WriteString(seg.Literal)
			case replace.SegmentFullMatch:
				result.WriteString(match.Match)
			case replace.SegmentCaptureIndex:
				result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
			}
		}

		lastEnd = absMatchEnd
		remaining = input[absMatchEnd:]
		offset = absMatchEnd
	}

	result.WriteString(input[lastEnd:])
	return result.String()
}

// ReplaceAllBytes replaces all matches in input using this compiled template.
func (t *DatePatternReplaceTemplate) ReplaceAllBytes(input []byte) []byte {
	return t.ReplaceAllBytesAppend(input, nil)
}

// ReplaceAllBytesAppend replaces all matches and appends to buf.
// If buf has sufficient capacity, no allocation occurs.
func (t *DatePatternReplaceTemplate) ReplaceAllBytesAppend(input []byte, buf []byte) []byte {
	result := buf[:0]
	lastEnd := 0
	var r DatePatternBytesResult

	remaining := input
	offset := 0

	for {
		match, ok := DatePattern{}.FindBytesReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := bytes.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		absMatchStart := offset + matchIdx
		absMatchEnd := absMatchStart + len(match.Match)

		result = append(result, input[lastEnd:absMatchStart]...)

		for _, seg := range t.segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result = append(result, seg.Literal...)
			case replace.SegmentFullMatch:
				result = append(result, match.Match...)
			case replace.SegmentCaptureIndex:
				result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
			}
		}

		lastEnd = absMatchEnd
		remaining = input[absMatchEnd:]
		offset = absMatchEnd
	}

	result = append(result, input[lastEnd:]...)
	return result
}

// ReplaceFirstString replaces only the first match using this compiled template.
func (t *DatePatternReplaceTemplate) ReplaceFirstString(input string) string {
	var r DatePatternResult
	match, ok := DatePattern{}.FindStringReuse(input, &r)
	if !ok {
		return input
	}

	matchIdx := strings.Index(input, match.Match)
	if matchIdx < 0 {
		return input
	}

	var result strings.Builder
	result.WriteString(input[:matchIdx])

	for _, seg := range t.segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result.WriteString(seg.Literal)
		case replace.SegmentFullMatch:
			result.WriteString(match.Match)
		case replace.SegmentCaptureIndex:
			result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
		}
	}

	result.WriteString(input[matchIdx+len(match.Match):])
	return result.String()
}

// ReplaceFirstBytes replaces only the first match using this compiled template.
func (t *DatePatternReplaceTemplate) ReplaceFirstBytes(input []byte) []byte {
	var r DatePatternBytesResult
	match, ok := DatePattern{}.FindBytesReuse(input, &r)
	if !ok {
		return append([]byte{}, input...)
	}

	matchIdx := bytes.Index(input, match.Match)
	if matchIdx < 0 {
		return append([]byte{}, input...)
	}

	var result []byte
	result = append(result, input[:matchIdx]...)

	for _, seg := range t.segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result = append(result, seg.Literal...)
		case replace.SegmentFullMatch:
			result = append(result, match.Match...)
		case replace.SegmentCaptureIndex:
			result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
		}
	}

	result = append(result, input[matchIdx+len(match.Match):]...)
	return result
}
