package main

import "sync"

// Code generated by regengo for pattern:
// DO NOT EDIT.

var digitStackPool = sync.Pool{New: func() interface{} {
	stack := make([][2]int, 0, 32)
	return &stack
}}

func DigitMatchString(input string) bool {
	l := len(input)
	offset := 0
	stackPtr := digitStackPool.Get().(*[][2]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [2]int{0, 0}
		}
		*stackPtr = stack[:0]
		digitStackPool.Put(stackPtr)
	}()
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			goto StepSelect
		}
		return false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins2
	}
Ins2:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 3
		} else {
			stack = append(stack, [2]int{offset, 3})
		}
		goto Ins1
	}
Ins3:
	{
		return true
	}
}
func DigitMatchBytes(input []byte) bool {
	l := len(input)
	offset := 0
	stackPtr := digitStackPool.Get().(*[][2]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [2]int{0, 0}
		}
		*stackPtr = stack[:0]
		digitStackPool.Put(stackPtr)
	}()
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			goto StepSelect
		}
		return false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x30) || input[offset] > uint8(0x39) {
			goto TryFallback
		}
		offset++
		goto Ins2
	}
Ins2:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 3
		} else {
			stack = append(stack, [2]int{offset, 3})
		}
		goto Ins1
	}
Ins3:
	{
		return true
	}
}
