package main

import (
	"regexp"
	"testing"
)

// Code generated by regengo
// Tests and benchmarks for pattern:

var digitRegexp = regexp.MustCompile("")

var testInputs = []string{"example"}

func TestDigitMatchString(t *testing.T) {
	for _, input := range testInputs {
		expected := digitRegexp.MatchString(input)
		got := DigitMatchString(input)
		if got != expected {
			t.Errorf("MatchString(%q) = %v, want %v", input, got, expected)
		}
	}
}

func TestDigitMatchBytes(t *testing.T) {
	for _, input := range testInputs {
		inputBytes := []byte(input)
		expected := digitRegexp.Match(inputBytes)
		got := DigitMatchBytes(inputBytes)
		if got != expected {
			t.Errorf("MatchBytes(%q) = %v, want %v", input, got, expected)
		}
	}
}

func BenchmarkDigitMatchString(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, input := range testInputs {
			_ = DigitMatchString(input)
		}
	}
}

func BenchmarkStdlibDigitMatchString(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, input := range testInputs {
			_ = digitRegexp.MatchString(input)
		}
	}
}
