package main

import (
	"regexp"
	"testing"
)

// Code generated by regengo
// Tests and benchmarks for pattern:

var emailRegexp = regexp.MustCompile("")

var testInputs = []string{"user@example.com", "test@test.org", "invalid"}

func TestEmailMatchString(t *testing.T) {
	for _, input := range testInputs {
		expected := emailRegexp.MatchString(input)
		got := EmailMatchString(input)
		if got != expected {
			t.Errorf("MatchString(%q) = %v, want %v", input, got, expected)
		}
	}
}

func TestEmailMatchBytes(t *testing.T) {
	for _, input := range testInputs {
		inputBytes := []byte(input)
		expected := emailRegexp.Match(inputBytes)
		got := EmailMatchBytes(inputBytes)
		if got != expected {
			t.Errorf("MatchBytes(%q) = %v, want %v", input, got, expected)
		}
	}
}

func TestEmailFindString(t *testing.T) {
	for _, input := range testInputs {
		expectedMatches := emailRegexp.FindStringSubmatch(input)
		result, ok := EmailFindString(input)

		if len(expectedMatches) > 0 {
			if !ok {
				t.Errorf("FindString(%q) returned false, expected match", input)
				continue
			}
			if result.Match != expectedMatches[0] {
				t.Errorf("FindString(%q).Match = %q, want %q", input, result.Match, expectedMatches[0])
			}
		} else {
			if ok {
				t.Errorf("FindString(%q) returned true, expected no match", input)
			}
		}
	}
}

func BenchmarkEmailMatchString(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, input := range testInputs {
			_ = EmailMatchString(input)
		}
	}
}

func BenchmarkStdlibEmailMatchString(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, input := range testInputs {
			_ = emailRegexp.MatchString(input)
		}
	}
}

func BenchmarkEmailFindString(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, input := range testInputs {
			_, _ = EmailFindString(input)
		}
	}
}

func BenchmarkStdlibEmailFindStringSubmatch(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, input := range testInputs {
			_ = emailRegexp.FindStringSubmatch(input)
		}
	}
}
