package main

import "sync"

// Code generated by regengo for pattern: (?P<user>[a-z]+)@(?P<domain>[a-z]+\.[a-z]+)
// DO NOT EDIT.

var email2StackPool = sync.Pool{New: func() interface{} {
	stack := make([][2]int, 0, 32)
	return &stack
}}

func Email2MatchString(input string) bool {
	l := len(input)
	offset := 0
	stackPtr := email2StackPool.Get().(*[][2]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [2]int{0, 0}
		}
		*stackPtr = stack[:0]
		email2StackPool.Put(stackPtr)
	}()
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			goto StepSelect
		}
		return false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		goto Ins2
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 4
		} else {
			stack = append(stack, [2]int{offset, 4})
		}
		goto Ins2
	}
Ins4:
	{
		goto Ins5
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x40) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 9
		} else {
			stack = append(stack, [2]int{offset, 9})
		}
		goto Ins7
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 12
		} else {
			stack = append(stack, [2]int{offset, 12})
		}
		goto Ins10
	}
Ins12:
	{
		goto Ins13
	}
Ins13:
	{
		return true
	}
}
func Email2MatchBytes(input []byte) bool {
	l := len(input)
	offset := 0
	stackPtr := email2StackPool.Get().(*[][2]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [2]int{0, 0}
		}
		*stackPtr = stack[:0]
		email2StackPool.Put(stackPtr)
	}()
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			goto StepSelect
		}
		return false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		goto Ins2
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 4
		} else {
			stack = append(stack, [2]int{offset, 4})
		}
		goto Ins2
	}
Ins4:
	{
		goto Ins5
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x40) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 9
		} else {
			stack = append(stack, [2]int{offset, 9})
		}
		goto Ins7
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 12
		} else {
			stack = append(stack, [2]int{offset, 12})
		}
		goto Ins10
	}
Ins12:
	{
		goto Ins13
	}
Ins13:
	{
		return true
	}
}

type Email2Match struct {
	Match  string // Full match
	User   string
	Domain string
}

func Email2FindString(input string) (*Email2Match, bool) {
	l := len(input)
	offset := 0
	captures := make([]int, 6)
	stackPtr := email2StackPool.Get().(*[][2]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [2]int{0, 0}
		}
		*stackPtr = stack[:0]
		email2StackPool.Put(stackPtr)
	}()
	captures[0] = 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			captures[0] = offset
			goto StepSelect
		}
		return nil, false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return nil, false
	}
Ins1:
	{
		captures[2] = offset
		nextInstruction = 2
		goto StepSelect
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 4
		} else {
			stack = append(stack, [2]int{offset, 4})
		}
		goto Ins2
	}
Ins4:
	{
		captures[3] = offset
		nextInstruction = 5
		goto StepSelect
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x40) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		captures[4] = offset
		nextInstruction = 7
		goto StepSelect
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 9
		} else {
			stack = append(stack, [2]int{offset, 9})
		}
		goto Ins7
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 12
		} else {
			stack = append(stack, [2]int{offset, 12})
		}
		goto Ins10
	}
Ins12:
	{
		captures[5] = offset
		nextInstruction = 13
		goto StepSelect
	}
Ins13:
	{
		captures[1] = offset
		return &Email2Match{
			Domain: string(input[captures[4]:captures[5]]),
			Match:  string(input[captures[0]:captures[1]]),
			User:   string(input[captures[2]:captures[3]]),
		}, true
	}
}
func Email2FindBytes(input []byte) (*Email2Match, bool) {
	l := len(input)
	offset := 0
	captures := make([]int, 6)
	stackPtr := email2StackPool.Get().(*[][2]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [2]int{0, 0}
		}
		*stackPtr = stack[:0]
		email2StackPool.Put(stackPtr)
	}()
	captures[0] = 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			captures[0] = offset
			goto StepSelect
		}
		return nil, false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	}
Ins0:
	{
		return nil, false
	}
Ins1:
	{
		captures[2] = offset
		nextInstruction = 2
		goto StepSelect
	}
Ins2:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 4
		} else {
			stack = append(stack, [2]int{offset, 4})
		}
		goto Ins2
	}
Ins4:
	{
		captures[3] = offset
		nextInstruction = 5
		goto StepSelect
	}
Ins5:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x40) {
			goto TryFallback
		}
		offset++
		goto Ins6
	}
Ins6:
	{
		captures[4] = offset
		nextInstruction = 7
		goto StepSelect
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 9
		} else {
			stack = append(stack, [2]int{offset, 9})
		}
		goto Ins7
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x61) || input[offset] > uint8(0x7a) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if cap(stack) > len(stack) {
			stack = stack[:len(stack)+1]
			stack[len(stack)-1][0] = offset
			stack[len(stack)-1][1] = 12
		} else {
			stack = append(stack, [2]int{offset, 12})
		}
		goto Ins10
	}
Ins12:
	{
		captures[5] = offset
		nextInstruction = 13
		goto StepSelect
	}
Ins13:
	{
		captures[1] = offset
		return &Email2Match{
			Domain: string(input[captures[4]:captures[5]]),
			Match:  string(input[captures[0]:captures[1]]),
			User:   string(input[captures[2]:captures[3]]),
		}, true
	}
}
