package regengo

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCompile(t *testing.T) {
	tests := []struct {
		name    string
		pattern string
		wantErr bool
	}{
		{
			name:    "simple pattern",
			pattern: "test",
			wantErr: false,
		},
		{
			name:    "email pattern",
			pattern: `[\w\.+-]+@[\w\.-]+\.[\w\.-]+`,
			wantErr: false,
		},
		{
			name:    "digit pattern",
			pattern: `\d+`,
			wantErr: false,
		},
		{
			name:    "invalid pattern",
			pattern: "[invalid",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			outputFile := filepath.Join(tmpDir, "test.go")

			opts := Options{
				Pattern:    tt.pattern,
				Name:       "Test",
				OutputFile: outputFile,
				Package:    "test",
			}

			err := Compile(opts)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Errorf("unexpected error: %v", err)
				return
			}

			// Verify output file exists
			if _, err := os.Stat(outputFile); os.IsNotExist(err) {
				t.Error("output file was not created")
			}

			// Verify output file contains expected functions
			content, err := os.ReadFile(outputFile)
			if err != nil {
				t.Errorf("failed to read output file: %v", err)
				return
			}

			contentStr := string(content)
			if !strings.Contains(contentStr, "func (Test) MatchString") {
				t.Error("output file does not contain MatchString method")
			}
			if !strings.Contains(contentStr, "func (Test) MatchBytes") {
				t.Error("output file does not contain MatchBytes method")
			}
		})
	}
}

func TestOptionsValidation(t *testing.T) {
	tests := []struct {
		name    string
		opts    Options
		wantErr bool
	}{
		{
			name: "valid options",
			opts: Options{
				Pattern:    "test",
				Name:       "Test",
				OutputFile: "test.go",
				Package:    "test",
			},
			wantErr: false,
		},
		{
			name: "empty pattern",
			opts: Options{
				Name:       "Test",
				OutputFile: "test.go",
				Package:    "test",
			},
			wantErr: true,
		},
		{
			name: "empty name",
			opts: Options{
				Pattern:    "test",
				OutputFile: "test.go",
				Package:    "test",
			},
			wantErr: true,
		},
		{
			name: "empty output file",
			opts: Options{
				Pattern: "test",
				Name:    "Test",
				Package: "test",
			},
			wantErr: true,
		},
		{
			name: "empty package",
			opts: Options{
				Pattern:    "test",
				Name:       "Test",
				OutputFile: "test.go",
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.opts.Validate()
			if tt.wantErr && err == nil {
				t.Error("expected validation error but got none")
			}
			if !tt.wantErr && err != nil {
				t.Errorf("unexpected validation error: %v", err)
			}
		})
	}
}

func TestCompileIntegration(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}

	tmpDir := t.TempDir()
	outputFile := filepath.Join(tmpDir, "email.go")

	opts := Options{
		Pattern:    `[\w\.+-]+@[\w\.-]+\.[\w\.-]+`,
		Name:       "Email",
		OutputFile: outputFile,
		Package:    "emailtest",
	}

	if err := Compile(opts); err != nil {
		t.Fatalf("compilation failed: %v", err)
	}

	// Read and verify the generated code
	content, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	contentStr := string(content)

	// Check for expected elements
	expectedElements := []string{
		"package emailtest",
		"func (Email) MatchString(input string) bool",
		"func (Email) MatchBytes(input []byte) bool",
		"// Code generated by regengo",
		"DO NOT EDIT",
	}

	for _, elem := range expectedElements {
		if !strings.Contains(contentStr, elem) {
			t.Errorf("generated code missing expected element: %q", elem)
		}
	}
}
